# =========================================================
# BASE DE DATOS DE BAREMOS (Fontanería)
# =========================================================
BAREMOS_DB = [
    ("a06", "Picado y tendido de yeso o escayola minimo 1cm de capa (m2)", "19.17"),
    ("a09", "moldura de escayola ( Hasta 3 ml servicio minimo )", "37.5"),
    ("a10", "moldura de escayola (Ml adicional )", "10.95"),
    ("a11", "Tapado de cala en techo o parametros verticales con enlucido ( hasta 1 m2 ) servicio minimo", "55.02"),
    ("a12", "tapado de cala con alicatado o solado ( material aportado por asegurado ) hasta 1m2", "52.52"),
    ("a13", "tapado de cala con alicatado o solado ( material aportado por profesional ) hasta 1m2", "68.52"),
    ("a14", "codigo adicional de tapado de cala con el enlucido. alicatado o solado (material aportado por asegurado) m2", "14.73"),
    ("a15", "codigo adicional de tapado de cala con el enlucido. alicatado o solado (material aportado por profesional) m2", "27.69"),
    ("a16", "reconstrucion de faldon de bañera", "40.5"),
    ("a19", "unicamente alicatado o solado ( hasta 3m precio por metro, material no incluido )", "29.13"),
    ("a20", "unicamente alicatado o solado ( mas 3m precio por metro, material no incluido ) se facturara el codigo a 19 mas adicional", "23.81"),
    ("a21", "m2 de solado de terrazo ( material no incluido )", "37.97"),
    ("a22", "tapar cala con hormigon en patios, garajes viviendas unifamiliares, etc ( hasta 1 m2 )", "70.9"),
    ("a23", "tapar cala con hormigon en patios, garajes viviendas unifamiliares, etc ( m2 adicional )", "47.17"),
    ("a28", "suministro y colocacion de armstrong o placa de escayola o tapado de cala con escayola ( hasta 1 m2  )", "51.16"),
    ("a29", "suministro y colocacion de armstrong o placa de escayola o tapado de cala con escayola (m2 adicional )", "26.37"),
    ("a30", "solera con cemento para posterior revestimiento ( parquet, moqueta) o sin terminacion ( no necesario colocar azulejo o badolsa ) hasta 1 m2 servicio minimo", "42.4"),
    ("a31", "solera con cemento para posterior revestimiento ( parquet, moqueta) o sin terminacion ( no necesario colocar azulejo o badolsa ) m2 adicional", "21.61"),
    ("a32", "suministro y colocacion de pavimento de sintasol o similar con cordon de sellado (m2)", "40.72"),
    ("a33", "tabicar o techar con pladur incluyendo perfileria de acero, lana de roca y placa ( primer metro, servicio minimo )", "76.5"),
    ("a34", "metro adicional de pladur incluyendo perfileria de acero, lana de roca y placa ( m2 adicional )", "46"),
    ("a43", "tapado con hormigon y posterior colocacion de alicatado o solado con material incluido aportado por el profesional ( hasta 1 m2)", "114"),
    ("a44", "tapado con hormigon y posterior colocacion de alicatado o solado con material incluido aportado por el profesional ( m2 adicional)", "90.98"),
    ("a45", "tapado con hormigon y posterior colocacion de alicatado o solado con material aportado por el asegurado ( hasta 1 m2 )", "94"),
    ("a46", "tapado con hormigon y posterior colocacion de alicatado o solado con material aportado por el asegurado ( m2 adicional )", "70.98"),
    ("ca38", "sustitucion de mueble de baño lacado en blanco o caracteristicas similares hasta 80 cm (incluye sustitucion de encimera lavabo y conexion de tomas )", "316.66"),
    ("ca39", "desmontaje y montaje de mueble de baño incluido encimera", "94.62"),
    ("cm2", "sustitucion o desmontaje y/o montaje de mampara incluye pequeño material en una unica visita", "78.71"),
    ("f01", "m2 picado en techo con escayola o enlucido", "9.3"),
    ("f02", "m2 picado en parametros verticales", "10.77"),
    ("f03", "m2 picado en parametros verticales con alicatado", "12.73"),
    ("f04", "m2 picado en suelos con gres, terrazo o similares", "12.63"),
    ("f05", "m2 picado en suelos de hormigon ( patio, garajes y etc )", "17.77"),
    ("f06", "m3 de excavacion y tapado de zanja ( para intervenciones mayores a 0.5 m3 )", "63.49"),
    ("f07", "codigo adicional de picado ( incluye cualquier tipo de picado)", "5.27"),
    ("f0c", "Localizacion de averia en comunidades. este codigo no puede coexistir con otro tipo de trabajo", "49.37"),
    ("f0h", "Localizacion de averia en hogar y comercio. este codigo no puede coexistir con otro tipo de trabajo", "34.5"),
    ("f10", "reparacion de bajante o ascendente", "58.56"),
    ("f101", "sustitucion mecanismo de carga (incluye mano de obra. material y Desmontaje y montaje cisterna en caso de ser necesario.) primera ud", "48.85"),
    ("f102", "sustitucion mecanismo de carga (incluye mano de obra. material y Desmontaje y montaje cisterna en caso de ser necesario.) ud adicional", "27.8"),
    ("f103", "sustitucion mecanismo de descarga (incluye mano de obra. material y Desmontaje y montaje cisterna en caso de ser necesario.) primera ud", "59.8"),
    ("f104", "sustitucion mecanismo de descarga (incluye mano de obra. material y Desmontaje y montaje cisterna en caso de ser necesario.) ud adicional", "39.53"),
    ("f105", "sustitucion mecanismo de carga y descarga(incluye mano de obra. material y Desmontaje y montaje cisterna en caso de ser necesario.) primera ud", "86.42"),
    ("f106", "sustitucion mecanismo de carga y descarga(incluye mano de obra. material y Desmontaje y montaje cisterna en caso de ser necesario.) ud adicional", "62.99"),
    ("f107", "unicamente sustitucion de tapa y/o asiento de sanitario sin sustitucion de loza", "39.53"),
    ("f108", "cambio de llave y detentor de radiador ud adicional", "23.92"),
    ("f109", "ud adicional de juego de latiguillos. adicional f41", "28.15"),
    ("f11", "sustitucion de t o y sencilla incluido tramo de tuberia general ( hasta 1 ml servicio minimo)", "112.32"),
    ("f110", "reparacion provisional ( con o sin elementos recuperables) (uno por servicio)", "39.27"),
    ("f111", "desmontaje y montaje de termo de mas de 50 L hasta 120L", "68.41"),
    ("f116", "plus por sustitucion de valvulas click clack o valvula sinfonica o sifones cromados", "15.3"),
    ("f12", "sustitucion de t o y doble incluido tramo de tuberia general ( hasta 1 ml servicio minimo)", "128.57"),
    ("f120", "sustitucion de conexion de inodoro ( mangueta)  rigido o elastico", "47.47"),
    ("f121", "sustitucion de conexion de inodoro ( mangueta)  flexible extensible", "54.58"),
    ("f122", "desmontaje y montaje de encimera de cocina. calentador o termo hasta 50l (ud) adicionales a otra reparacion", "36.72"),
    ("f13", "sustitucion de tramo de tuberia general ( hasta 1 ml servicio minimo)", "66.96"),
    ("f14", "sustitucion de tramo de tuberia general ( ud adicional )", "14.93"),
    ("f15", "sustitucion de bajante vista de pluviales. bajantes fecales y/o no vistas ( hasta 3 ml servicio minimo )", "96.93"),
    ("f16", "sustitucion de bajante vista de pluviales. bajantes fecales y/o no vistas ( ud adicional )", "36.35"),
    ("f17", "sustitucion de canalon pvc sin andamio ( ml )", "34.21"),
    ("f18", "sustitucion de canalon zinc o aluminio sin andamio ( ml )", "40.34"),
    ("f19", "sustitucion de canalon de cobre ( ml )", "59.75"),
    ("f20", "reparacion de mangueton", "46.53"),
    ("f21", "reparacion de bote sinfonico", "49.35"),
    ("f22", "reparacion de valvula y/o sifon ( bañera, lavabo, bidet, fregadero y ducha )", "37.44"),
    ("f22_M", "reparacion de valvula y/o sifon ( bañera, lavabo, bidet, fregadero y ducha )", "36.69"),
    ("f23", "reparacion de tuberia con soldadura/ anulacion de tomas", "42.48"),
    ("f24", "reparacion de mecanismo de cisterna ( mano de obra y material )", "39.02"),
    ("f25", "reparacion tuberia con abrazadera, gebo tapa poros hasta 1", "50.38"),
    ("f27", "reparacion tuberia con abrazadera, gebo tapa poros mas de 1", "57.54"),
    ("f29", "reparacion de grifo, llave de paso ( mano de obra y material )", "38.9"),
    ("f29_M", "reparacion de grifo, llave de paso ( mano de obra )", "38.12"),
    ("f30", "sustitucion de tramo de tuberia de desague, alimentacion o calefaccion en plomo, pvc o cobre. 1 ml", "49.65"),
    ("f31", "sustitucion de tramo de tuberia de desague, alimentacion o calefaccion en plomo, pvc o cobre. ud adicional", "13.24"),
    ("f32", "sustitucion de tuberia de alimentacion ( fria y caliente ) o calefaccion ( ida y retorno ) hasta 2 m", "69.22"),
    ("f33", "sustitucion de T y/o Y  de alimentacion, Desague o calefaccion incluidos tramos y manguitos", "69.01"),
    ("f34", "sustitucion de mangueton de pvc ( desmontaje y montaje de inodoro y tramo de desague incluido )", "123.44"),
    ("f35", "sustitucion de mangueton de pvc acoplado a desmbarco de plomo ( incluido montaje y desmontaje de inodoro )", "145.96"),
    ("f36", "sustitucion de valvula sin rebosadero incluyendo tramo de desague hasta 1 ml", "43.47"),
    ("f37", "sustitucion de valvula y rebosadero o sifon incluyendo tramo de desague hasta 1 ml", "52.35"),
    ("f38", "sustitucion de bote sinfonico de pvc ( empalmes y soldaduras hasta 5 salidas incluidos )", "107.63"),
    ("f40", "sustitucion de sifon", "42.06"),
    ("f41", "sustitucion de latiguillos causando daños propios y/o a terceros (servicio minimo)", "41.08"),
    ("f41_M", "sustitucion de latiguillos causando daños propios y/o a terceros (servicio minimo)", "34.56"),
    ("f42", "reparacion de radiador (mano de obra y material )", "41.27"),
    ("f43", "modificacion o sustitucion de tomas en siniestros de loza con cambio de modelo por estar descatalogado", "30.32"),
    ("f44", "sustitucion de grifo ( no incluye material ) primera ud", "42.67"),
    ("f45", "sustitucion de grifo ( no incluye material ) ud adicional", "18.22"),
    ("f46", "sustitucion de llave de paso. 1º llave. servicio minimo (incluye material )", "52.08"),
    ("f46_M", "sustitucion de llave de paso. 1º llave. servicio minimo (incluye material )", "39.06"),
    ("f47", "sustitucion de llave de paso. ud adicional . servicio minimo (incluye material )", "19.75"),
    ("f48", "sustitucion de radiador, no cubre material", "47.04"),
    ("f49", "desmontaje y/o montaje de mampara o columna de hidromasaje con otra reparacion", "50.2"),
    ("f50", "unicamente sustitucion de sanitario (ud. lavabo, bidet o inodoro, fregadero )", "45.75"),
    ("f51", "unicamente sustitucion de sanitario (ud. plato de ducha)", "132.8"),
    ("f52", "unicamente sustitucion de sanitario (ud. bañera)", "111.8"),
    ("f53", "desmontaje y montaje de ud de sanitarios (ud. lavabo,bidet o inodoro)", "28.2"),
    ("f54", "desmontaje y montaje de unidad de sanitarios (ud. plato ducha)", "98.59"),
    ("f55", "desmontaje y montaje de unidadde sanitarios (ud. bañera)", "82.5"),
    ("f56", "desmontaje y montaje de mueble cocina. mueble de baño. fregadero. radiador. adicionales a otra reparacion", "28.62"),
    ("f57", "sellado de banda de bañera o plato de ducha con silicona o cemento blanco.", "38.96"),
    ("f58", "cambio de llave y detentor de radiador", "42.87"),
    ("f59", "vaciado y llenado de circuito de calefaccion con purgado de radiadores (hasta 10 radiadores)", "37.5"),
    ("f60", "sustitucion de tuberia de polietileno reticulado/ multicapa, polibutileno, polipropileno o similares. 1 m", "76.81"),
    ("f61", "sustitucion de tuberia de polietileno reticulado/ multicapa, polibutileno, polipropileno o similares. ud adicional", "36.74"),
    ("f62", "desatranco manual o con liquido desatascador ( incluido material y mano de obra ) ( codigo unico por servicio )", "47.42"),
    ("f63", "desatranco con medios mecanicos (incluido material y mano de obra). primera hora. obligatorio aportar fografia de la maquina", "70.14"),
    ("f64", "desatranco con medios mecanicos (incluido material) hora adicional", "31.1"),
    ("f65", "sustitucion o desmontaje y/o montaje de mampara. codigo unico por servicio. no podra coexistir con otro codigo", "78.71"),
    ("f66", "ajuste de elementos sanitarios (mano de obra y material)", "35.73"),
    ("f67", "sustitucion de gomas de tomas y desagues de electrodomesticos (mano de obra y material )", "39.25"),
    ("f68", "material loza sanitaria. indicar marca y modelo", "Precio manual"),
    ("f69", "suplemento por sustitucion de tuberia por rotura en realizacion de desatranco", "14.09"),
    ("f70", "desmontaje y montaje de griferia o llave de paso (acompñado de otra reparacion)", "11.74"),
    ("f77", "sustitucion de valvula sin rebosadero. en sustitucion de sanitarios y ud adicionales", "16.67"),
    ("f78", "sustitucion de valvula con rebosadero. en sustitucion de sanitarios y ud adicionales", "28.31"),
    ("f79", "sustitucion de sifon (2º y sucesivos. adicional", "8.91"),
    ("f81", "desatranco manual con liquido desatascador ( incluido material y mano de obra) desatasco adicional", "28.36"),
    ("f89", "reparacion adicional comun (excepto para el codico f23)", "25.78"),
    ("f90", "reparacion adicional con soldadura(soldadura adicional)", "6.78"),
    ("f91", "material griferia. indicar marca y modelo", "Precio manual"),
    ("f92", "sustitucion de caldera (montaje y desmontaje) (vaciado y llenado del circuito incluido)", "126"),
    ("f93", "modificacion o sustitucion de tomas existentes para sustitucion de calderas", "64"),
    ("f95", "desmontaje y/o montaje de mampara. codigo unico por servicio. no podra coexistir con otra reparacion", "100.4"),
    ("f96", "cambio de plato de ducha (sin material) incluye 1 m2 de picado. tapado. solera y saco de escombros", "332.56"),
    ("f97", "cambio de plato de ducha (sin material) incluye desmontaje y/o montaje de mampara. incluye 1 m2 de", "411.27"),
    ("IM", "intervencion minima fontanero", "34.5"),
    ("M", "materiales", "Precio manual"),
    ("ma25", "sustitucion superficies marmol o granito nacional m2. grosor 2 cm ( tapas de mesa. escalones o similares", "135"),
    ("ma26", "sustitucion superficies marmol o granito importacion m2 grosor 2 cm ( tapas de mesa escalones o similares )", "201"),
    ("ma27", "sustitucion de encimera de marmol de importacion hasta 1.20 ml (incluido copete y encastre) grosor 2 cm", "343.9"),
    ("ma28", "sustitucion de encimera de marmol de importacion hasta 1.20 ml (incluido copete y encastre) grosor 3 cm", "380.62"),
    ("ma29", "sustitucion de encimera de marmol de importacion ml adicional (incluido copete y encastre) grosor 2 cm", "273.13"),
    ("ma30", "sustitucion de encimera de marmol de importacion ml adicional (incluido copete y encastre) grosor 3 cm", "315.96"),
    ("m0", "mano de obra fontanero", "26"),
    ("m0a", "mano de obra ayudante", "15"),
    ("T01", "subida al tejado y confeccion de presupuesto ( codigo unico por servicio ) incluye alquiler de escalera", "68.58"),
    ("t04", "suministro y colocacion de tejas (hormigon, ceramica)  de 1 a 2 m2", "155.82"),
    ("t05", "suministro y colocacion de tejas (hormigon, ceramica)  ml adicional", "60.76"),
    ("t06", "suministro y colocacion de tejas ( pizarra, arabe) de 1 a 2 m2", "175.22"),
    ("t07", "suministro y colocacion de tejas ( pizarra, arabe) ml adicional", "71.05"),
    ("t08", "impermeabilizacion de superficie mediante tela asfaltica (cualquier tipo ) hasta 2 m2", "66.8"),
    ("t09", "impermeabilizacion de superficie mediante tela asfaltica (cualquier tipo ) ml adicional", "18.9"),
    ("t10", "reparacion de caballetes y o limas sustituyendo tejas de 1 a 4 ml", "175"),
    ("t11", "reparacion de caballetes y o limas sustituyendo tejas ml adicional", "40"),
    ("t12", "impermeabilizacion de terraza/tejado con tela asfaltica y posterior impermeabilizacion con brea y clorocaucho ( chimenea, laterales y etc ) 1 m2", "130"),
    ("t13", "impermeabilizacion de terraza/tejado con tela asfaltica y posterior impermeabilizacion con brea y clorocaucho ( chimenea, laterales y etc ) ml adicional", "60"),
    ("t14", "reparacion de terraza impermeabilizacion con clorocaucho/ fibra de vidrio 1 m2", "50"),
    ("t15", "reparacion de terraza impermeabilizacion con clorocaucho/ fibra de vidrio ml adicional", "30"),
    ("t16", "unicamente recolocacion de tejas existentes hasta 4 m2", "88"),
    ("t17", "unicamente recolocacion de tejas existentes ml adicional", "18.8"),
    ("tec2", "reparacion o sustitucion de cualquier electrodomestico de gama blanca ( incluye vitro de cortesia si", "67.06"),
    ("tec4", "reparacion o sustitucion de cualquier electrodomestico de gama blanca ( incluye vitro de cortesia si  ud adicional", "34.5"),
    ("VI", "visita infructuosa no se realizan trabajos en la vivienda", "24"),
    ("x01", "alquiler de andamios incluso tralado a obra (montaje y desmontaje hasta 2 cuerpos", "88.2"),
    ("x02", "alquiler de andamios incluso tralado a obra (montaje y desmontaje hasta 3 cuerpos", "117.52"),
    ("x03", "alquiler de andamios incluso tralado a obra (montaje y desmontaje hasta 4 cuerpos", "153.67"),
    ("x04", "alquiler de andamios incluso tralado a obra (montaje y desmontaje hasta 5 cuerpos", "187.88"),
    ("x05", "alquiler de andamios incluso tralado a obra (montaje y desmontaje hasta 6 cuerpos", "220.45"),
    ("x06", "alquiler de contenedor minimo 1 m3 de desescombro", "105.83"),
    ("x07", "utilizacion de saco para escombro incluido gestion de residuos del mismo con capacidad 1 m3", "48.89"),
    ("x08", "escalera telescopica/ alquiler martillo compresor o pistolete o martillo electrico ( solo para superficies de hormigon tales como rampas, garajes, patios )", "34.44"),
    ("x09", "plus peligrosidad, utilizacion de arneses", "174.6"),
    ("x13", "alquiler grua especial elevadora de gran tonelaje y dimensiones mas de 12 m de brazo (imprescindible factura)", "Importe manual"),
    ("x14", "alquiler camion/ grua elevadora ( con o sin cesta)", "275"),
    ("x15", "trabajos verticales ( descolgados )", "Importe manual")
]
